models first version
GlebZhnkvch/Car_showroom_MS_test pull request #1
Opened 2021-07-07 23:01 UTC by GlebZhnkvch

2021-07-08 07:41 UTC, Ivan-Soldatenko requested changes

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Car_showroom_ms/settings.py
> +environ.Env.read_env()
Используй модуль os

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Car_showroom_ms/settings.py
> +SECRET_KEY = env('SECRET_KEY')
По типу `os.environ.get('SECRET_KEY')`

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Dockerfile
> +RUN pip3 install -r requirements.txt
requirements должны храниться в pipenv (Pipfiles), а не в отдельном txt файле.

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Pipfile
> +django-environ = "*"
Лишнее в данном случае

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on requirements.txt
> +sqlparse==0.4.1; python_version >= '3.5'
requirements хранятся с помощью pipenv (Pipfiles)

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=DATABASE_PASSWORD
Используй `env_file`

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Dockerfile
> +CMD ["python", "manage.py", "runserver"]
Создать entrypoint.sh (консольный скрипт), который будет запускать веб - приложение только после того, как база данных поднимется

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Dockerfile
> +FROM python:3.8
Используй последнюю версию python (3.9.x)

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on Dockerfile
> +WORKDIR /usr/src/Car_showroom_MS_test/
Слишком большая иерархия директорий, достаточно просто `/app/`

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on docker-compose.yml
> +    command: python3 manage.py runserver
Добавить `entrypoint.sh`

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    brand = models.CharField(max_length=50)
manufacturer больше подходит

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +                                           )
Странный code style. Используйте black для форматирования кода

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    cars = models.ForeignKey(Car, on_delete=models.CASCADE)
M2M, поставщик может продавать несколько автомобилей и один и тот же автомобиль может продаваться у разных поставщиков

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    default = 0,
Опечатка?

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    customers = models.ForeignKey('Customer', on_delete=models.CASCADE)
M2M поле

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +                                               blank=True)
странный code style

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    purchases_history = models.ForeignKey('CarShowRoomPurchase', on_delete=models.CASCADE)
Лишние поля

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +                                              default=0)
code style

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    car = models.ForeignKey(Car, on_delete=models.CASCADE)
M2M поле

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    car = models.ForeignKey(Car, on_delete=models.CASCADE)
M2M поле

2021-07-08 07:41 UTC, Ivan-Soldatenko commented on users/models.py
> +        pass
Дореализуй модель юзера

2021-07-08 07:48 UTC, Ivan-Soldatenko commented
В целом неплохо, но я хотел, чтобы были созданы абстрактные модели, которые бы хранили поля soft_delete для удаления объекта, creation_time для времени создания объекта и updated_at для времени последнего обновления. Причем для каждого из полей должна быть создана отдельная абстрактная модель. Ветки нужно называть в формате `feature/<branch_name>` или `fix/<branch_name>`. Поэтому `models-feature`  - неверное название.

2021-07-10 16:36 UTC, Ivan-Soldatenko requested changes

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +FROM python:3.8
Версия так и не была обновлена

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +RUN pip3 install pipenv
Можно объединить с установкой всех зависимостей, поэтому выражение лишнее

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +WORKDIR /usr/src/Car_showroom_MS_test/
для упрощения лучше использовать либо просто `/app/`  либо `/usr/src/app/`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +COPY ./Pipfile.lock .
Можно объединить, написав `COPY Pipfile* /usr/src/app/`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +RUN pipenv install --system --deploy --ignore-pipfile
Объединить с установкой `pipenv` - `RUN pip install pipenv && pipenv install --deploy --system --ignore-pipfile`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +COPY . /usr/src/car_showroom_ms_test/
`COPY ./entrypoint.sh .` - лишнее, так как в следующем выражении весь проект копируется в директорию в контейнере, в том числе и `entrypoint.sh` -> `COPY . /usr/src/app/`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on Dockerfile
> +
Пустая строка в конце файла не нужна.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/admin.py
> +from car_showroom.models import Customer, Car, CarSupplier, CarShowRoom, CarShowRoomAction, CarSupplierAction
Логически разделять импорты на группы, связанные с тем или иным фраймворком / библиотекой или разные django app

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/admin.py
> +from car_showroom.models import Customer, Car, CarSupplier, CarShowRoom, CarShowRoomAction, CarSupplierAction
`from car_showroom.models` - слишком длинный импорт, лучше сделать многострочным

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/admin.py
> +from car_showroom.models import Customer, Car, CarSupplier, CarShowRoom, CarShowRoomAction, CarSupplierAction
По итогу должно получиться что - то подобное:
![image](https://user-images.githubusercontent.com/66316921/125169561-713ab300-e1b3-11eb-91a6-76adb1fc97bc.png)

Примечание: импорты сортируются по убыванию, как показано выше.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/admin.py
> +admin.site.register(Customer)
Реализовать подключение моделей к админ - панеле с помощью классов, при этом кастомизировать ее поведение, используя поля по типу `list_display` или `list_filter`.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on entrypoint.sh
> +if [ "$DATABASE" = "postgres" ]
Для читаемости между выделенными выражениями добавить пустую строку

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on entrypoint.sh
> +exec "$@"
Пустую строку между выражениями

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on docker-compose.yml
> +    ports:
Добавить `restart:` секцию.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on docker-compose.yml
> +      - "8000:8000"
Лучше написать без кавычек -> `8000:8000`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    location = CountryField()
Отдельная модель для `location`, которая будет хранить: страну, город, улицу, номер здания.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    car_model = models.CharField(max_length=50, blank=True)
FK на `car` вместо этих полей

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    purchase_time = models.DateTimeField(auto_now=True)
лишнее поле, можно использовать `creation_time` из `CreatedAt`

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    purchase_time = models.DateTimeField(auto_now=True)
Лишнее поле

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    sale_time = models.DateTimeField(auto_now_add=True)
Лишнее поле

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +class CarShowRoomPurchase(SoftDelete, CreatedAt, UpdatedAt):
Добавить поле с суммой сделки.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +class CustomerPurchase(SoftDelete, CreatedAt, UpdatedAt):
Добавить поле с суммой сделки.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +class CarShowRoomSale(SoftDelete, CreatedAt, UpdatedAt):
Добавить поле с суммой сделки.

2021-07-10 16:36 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +    cars_quantity = models.IntegerField()
Лучше использовать `models.PositiveSmallInteger`

2021-07-10 21:52 UTC, Ivan-Soldatenko requested changes
1. Стоило бы разделить одно большое приложение `car_showroom` на мелкие, например на `customers`, `car_showrooms`, `suppliers`.
2. Подключить модели к админке, используя классы и кастомизировать админку с помощью `list_display`, `list_filter` и т.д.
3. Нужно изменить структуру своего проекта на следующую:
![image](https://user-images.githubusercontent.com/66316921/125177151-26845f80-e1e2-11eb-942a-db254179aa92.png)
Локальные приложения должны находиться внутри верхней директории `car_dealership`.

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on Car_showroom_ms/settings.py
> +DEBUG = os.environ.get('DEBUG')
По дефолту True лучше сделать, чтобы `DEBUG = FALSE` только тогда, когда это действительно нужно.

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on Dockerfile
> +RUN pip3 install pipenv
Это выражение можно удалить, `pipenv` установится ниже перед установкой зависимостей

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on Dockerfile
> +ENV PYTHONUNBUFFERED 1
Объявление `ENV` переменных обычно помещают выше `WORKDIR`

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on docker-compose.yml
> +
3 пустых строки лишние, 1 - достаточно

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on entrypoint.sh
> +fi
Эта часть работать не будет, т.к. переменные окружения `DATABASE`, `SQL_HOST`, `SQL_PORT`

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on entrypoint.sh
> +fi
Проверку с переменной `DATABASE` можно удалить, т.к. у нас и так подразумевается, что используется postgres

2021-07-10 21:52 UTC, Ivan-Soldatenko commented on car_showroom/models.py
> +from django.core.validators import MaxValueValidator, MinValueValidator
Импорты должны идти по убыванию, а не возрастанию

2021-07-13 16:35 UTC, isoldatenko requested changes
По структуре проекта все хорошо. Но `migrations` почему - то попали в пулл реквест, нужно исправить.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    location = models.ForeignKey(Location, on_delete=models.CASCADE)
Вряд ли мы хотим, чтобы пользователь удалялся после удаления локации, лучше используй `models.SET_NULL`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    maximum_price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
`blank = False` стоит по дефолту, можно не указывать явно.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    car_showroom = models.ForeignKey('car_showrooms.CarShowRoom', on_delete=models.ForeignKey)
Если автосалон или автомобиль удалится, история должна остаться, поэтому нужно использовать `on_delete=models.SET_NULL`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    customer = models.ForeignKey('customers.Customer', on_delete=models.CASCADE)
Указать `related_name` и `related_query_name`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    car_showroom = models.ForeignKey('car_showrooms.CarShowRoom', on_delete=models.ForeignKey)
Указать `related_name='+'`, чтобы обратная связь не создавалась вообще, так как нам неинтересны покупки клиента с точки зрения автосалона (имеет свою историю) и машин

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +class CustomerPurchase(SoftDelete, CreatedAt, UpdatedAt):
Добавить метод `__str__`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    car = models.ForeignKey(Car, on_delete=models.CASCADE)
Указать `related_name='+'`, так как обратная связь нам неинтересна.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    location = models.ForeignKey(Location, on_delete=models.CASCADE)
Указать `related_name='+'`, так как обратная связь нам неинтересна.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/admin.py
> +    list_filter = ('location__city', )
Полезным будет также `location__country`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/admin.py
> +    search_fields = ('customer__email' 'bought_car__manufacturer', 'car_showroom__name')
Можно добавить еще `bought_car__model`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/admin.py
> +    search_fields = ('car__manufacturer', 'car_model')
`car__model` -  два нижних подчеркивания нужно

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/customers/admin.py
> +from customers.models import (Customer, CustomerPurchase, Offer)
Скобки лишние.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/core/models.py
> +        abstract = True
Пустую строку нужно оставлять в конце `.py` файла

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    manufacture_year = models.IntegerField(validators=[MinValueValidator(1980), MaxValueValidator(2021)])
Поля должны быть уникальны вместе, добавить constraint

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +                                              default=0)
Процент скидки должен начинаться хотя бы с 1 (процент скидки равный 0, по факту не является скидкой)

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    title = models.CharField(max_length=255)
Название должны быть уникальным.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car = models.ManyToManyField(Car)
M2M (многие ко многим) поле должно быть во множественном числе (cars)

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car = models.ManyToManyField(Car)
Добавить `related_name='+'`, так как нас не интересует обратная связь

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    building_number = models.PositiveSmallIntegerField()
Должны быть уникальны вместе, добавить constraint.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    location = models.OneToOneField(Location, on_delete=models.CASCADE)
Поставщик не должен удалятся при удалении локации. Используй `models.SET_NULL`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    cars = models.ManyToManyField(Car)
Добавить `related_name`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    customers = models.ManyToManyField('car_showrooms.CarShowRoom', blank=True)
Добавить `null=True` в данном случае, если добавлен `blank=True`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car_supplier = models.ForeignKey(CarSupplier, on_delete=models.CASCADE)
Добавить `related_name` и `related_query_name`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    customers = models.ManyToManyField(Customer, blank=True)
Добавить `null=True` в этом случае, если добавлен `blank=True`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    cars_in_stock = models.ManyToManyField(Car, through='CarInfo', through_fields=('car_showroom', 'car',))
Добавить `related_name`.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    location = models.OneToOneField(Location, on_delete=models.CASCADE)
Автосалон не должен удалятся при удалении локации

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    preferred_car_minimum_foundation_year = models.CharField(max_length=50)
Добавить `blank=True` к этим полям, так как они могут оставаться пустыми, это означает что автосалон не интересуется каким либо конкретным производителем и т.д.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    car_showroom = models.ForeignKey(CarShowRoom, on_delete=models.CASCADE)
Сделка не должна удалятся при удалении автомобиля / автосалона.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    sale_amount = models.DecimalField(max_digits=10, decimal_places=2)
Нужна ли нам эта модель, если у нас уже есть `CustomerPurchase`, что по сути одно и то же.

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    bought_car = models.ForeignKey(Car, on_delete=models.CASCADE)
Добавить `related_name='+'`

2021-07-13 16:35 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    car_showroom = models.ForeignKey(CarShowRoom, on_delete=models.CASCADE)
Добавить `related_name` для обратной связи.

2021-07-14 22:32 UTC, isoldatenko requested changes
Используй следующий линты для правильного форматирования кода:
1. flake8 - проверяет код стайл по PEP8 и выводит сообщения о строках с неправильным оформлением (с точной причиной)
2. black - для автоматического форматирования кода по PEP8

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/Dockerfile
> +
Лишняя пустая строка

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +    CarShowRoom,
Сортируй по убыванию длины

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/admin.py
> +    Car,
Сортируй по убыванию длины

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    cars_in_stock = models.ManyToManyField(
Для упрощения лучше назвать либо просто `cars` либо `available_cars` или что - то наподобие этого

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    customers = models.ManyToManyField(Customer, null=True)
Установи `related_name='+'`, т.к. нам не нужна обратная связь на автосалон от клиента

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    preferred_car_minimum_foundation_year = models.CharField(max_length=50, blank=True)
Лучше использовать`JSONField`, так как он обеспечивает гибкость и позволяет огромное количество различных характеристик в одном поле, не добавляя новые поля в модель

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    car_supplier = models.ForeignKey('car_suppliers.CarSupplier', on_delete=models.ForeignKey, related_name='clients')
При удалении поставщика / машины сделка должна оставаться для автосалона, используй `models.SET_NULL`

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +        unique_together = ['manufacturer', 'model', 'manufacture_year', ]
Используй `tuple` вместо `list`

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    manufacturer = models.CharField(max_length=50)
Вынеси `manufacturer` в отдельную модель с дополнительной информацией о производителях.

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    building_number = models.PositiveSmallIntegerField()
Добавить упомянутый выше unqiue constraint.

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    foundation_date = models.DateField()
Лучше `foundation_time`  и использовать `models.DateTimeField`

2021-07-14 22:32 UTC, isoldatenko commented on docker-compose.yml
> +      - car_showroom_ms/.env
Это работает без `./` в начале пути?

2021-07-14 22:32 UTC, isoldatenko commented on docker-compose.yml
> +      - car_showroom_ms/.env
Это работает без ./ в начале пути?

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +class Customer(SoftDelete, CreatedAt, UpdatedAt, models.Model):
Наследоваться в этом случае еще и от `models.Model` является лишним.

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    purchase_amount = models.DecimalField(max_digits=10, decimal_places=2)
Для каждой покупки пользователя должна создаваться отдельная модель сделки, поэтому это поле является лишним.

2021-07-14 22:32 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    purchase_amount = models.DecimalField(max_digits=10, decimal_places=2)
Нужно добавить поле для хранения суммы сделки

2021-07-15 20:13 UTC, isoldatenko requested changes
На счет структуры в `core`. Добавить туда `python package` с названием `models`, в ней создать `python module` с названием `abstract_models` и уже там хранить абстрактные модели. Также нужно разобраться с `,gitignore` и полностью удалить `migrations` из `git`

2021-07-15 20:13 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +        return f'{self.title}'
`f'{self.title} {self.car_supplier} {self.discount_percentage} (self.action_start_time - self.action_end_time)'`

2021-07-15 20:13 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/admin.py
> +    ordering = ('manufacturer',)
Сделать фильтрацию / поиск по каким - то конкретным полям производителя

2021-07-15 20:13 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/admin.py
> +    ordering = ('action_start_time',)
Будет ли работать поиск / фильтрация по полю `manufacturer` после вынесения производителя в отдельную модель?

2021-07-15 20:13 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    building_number = models.PositiveSmallIntegerField()
Должны быть уникальны вместе.

2021-07-16 20:46 UTC, isoldatenko requested changes

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/core/models/abstract_models.py
> +from django.core.validators import MinValueValidator, MaxValueValidator
импорты по убыванию

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/core/models/abstract_models.py
> +    title = models.CharField(max_length=255, unique=True)
Слишком большая длина для названия, 100 символов должно быть достаточно

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/core/models/abstract_models.py
> +    description = models.TextField()
Описание может быть пустым (`blank=True`)

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/core/models/abstract_models.py
> +    discount_percentage = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
Используй `tuple` вместо `list` (для `validators`)

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    balance = models.DecimalField(max_digits=10, decimal_places=2)
Добавить больше полей для описания клиента, по типу возраста, пола и т.д.

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    description = models.TextField()
Описание может быть пустым (`blank=True`)

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car_body = models.CharField(max_length=25)
Кузов автомобиля имеет ограниченный выбор, добавить `choices`, используя `enum`

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    engine_capacity = models.DecimalField(max_digits=4, decimal_places=1)
Поле не может быть отрицательным

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +        return f'{self.car} - {self.car_supplier}'
Лучше вынести в абстрактную модель, так как `CarInfo` используется в автосалоне

2021-07-16 20:46 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +from django_countries.fields import CountryField
импорты из библиотек должны идти выше импортов из локальных пакетов

2021-07-17 20:08 UTC, isoldatenko requested changes

2021-07-17 21:03 UTC, isoldatenko requested changes

2021-07-17 21:03 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/models.py
> +    purchase_amount = models.DecimalField(max_digits=10, decimal_places=2)
Вынести в абстрактную модель, так как аналогичная модель используется в `customers` -> `CustomerPurchase`

2021-07-17 21:03 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +from core.models.abstract_models import SoftDelete, CreatedAt, UpdatedAt, Action, CarInfo
по убыванию

2021-07-17 21:03 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car_body = models.CharField(choices=CarBodyTypes.choices(), max_length=50)
Перепроверить `Max_length`, исходя из содержимого `enum`

2021-07-17 21:03 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +class CarSupplier(SoftDelete, CreatedAt, UpdatedAt):
Добавить поле с описанием поставщика

2021-07-18 08:32 UTC, isoldatenko requested changes

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/core/models/abstract_models.py
> +        abstract = True
Думаю, что эти модели лучше отделить от остальных и вынести в модуль по типу `base_models`

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/car_showroom_ms_test/settings.py
> +SECRET_KEY = os.environ.get('SECRET_KEY', 'rmgfkl;ge')
Убрать дефолтный ключ

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    description = models.TextField()
Может быть пустым

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    manufacturer = models.ForeignKey(CarManufacturer, on_delete=models.CASCADE, related_name='cars')
Удаление машин может привести к ошибках, поэтому их удалять нужно безопасно. Поэтому нужно использовать `on_delete=models.PROTECT`, чтобы удалить производителя можно было в том случае, если все связанные с ним автомобили уже удалены.

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    foundation_time = models.DateTimeField()
`foundation_date` будет достаточно

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    gender = models.CharField(choices=GenderTypes.choices(), blank=True, max_length=6)
`max_length` лучше указывать в качестве первого аргумента

2021-07-18 08:32 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +    car_body = models.CharField(choices=CarBodyTypes.choices(), max_length=13)
`max_length` лучше указывать в качестве первого аргумента

2021-07-18 13:45 UTC, isoldatenko requested changes

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +class CarShoRoomCarInfoAdmin(admin.ModelAdmin):
`CarShowRoomCarInfoAdmin` -> опечатка

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +    ordering = ("name",)
Сортировка по имени, а затем по балансу в обратном порядке

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +        "car__car_body" "car_showroom__name",
Пропущена запятая

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +    )
Можно вывести еще количество купленных машин

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +    ordering = ("-purchase_amount",)
Затем сортировка по количеству купленных машин

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_showrooms/admin.py
> +    ordering = ("action_start_time",)
Затем поп проценту скидки

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/admin.py
> +    )
В данном случае в сортировку можно внести все поля

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/admin.py
> +        "location__city",
Дубликаты

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +
Лишняя пустая строка

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +from django.core.validators import MinValueValidator, MaxValueValidator
После удаления лишней пустой строки - импорты сортируются по убыванию

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/customers/admin.py
> +        "customer__email" "bought_car__manufacturer__name",
Пропущена запятая

2021-07-18 13:45 UTC, isoldatenko commented on car_showroom_ms/car_suppliers/models.py
> +from decimal import Decimal
Этот импорт нужно поставить на первое место и отделить от других, т.к. импорт из стандартной библиотеки питона

2021-07-18 20:08 UTC, isoldatenko requested changes

2021-07-18 20:08 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +class Customer(SoftDelete, CreatedAt, UpdatedAt):
Добавить поле с номер телефона и валидатором на телефон в белорусском формате

2021-07-18 20:08 UTC, isoldatenko commented on car_showroom_ms/customers/models.py
> +    user = models.OneToOneField("users.User", on_delete=models.CASCADE)
`related_name` нужно добавить

2021-07-18 20:08 UTC, isoldatenko commented on car_showroom_ms/users/models.py
> +        pass
Необязательно это писать явно

2021-07-19 09:03 UTC, isoldatenko approved these changes

2021-07-19 09:11 UTC, merged